spring:
  application:
    name: demo-service
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://192.168.205.5:27017/kotlin-demo-db
      uuid-representation: standard
server:
  servlet:
    context-path: /kotlin-demo
  shutdown: graceful

logging:
  level:
    web: TRACE
    org.springframework.web: TRACE